### PR TITLE
included tsconfig-paths in worker.js

### PR DESCRIPTION
**Pull request by kgkg**
Hello,

this PR adds tsconfig-paths registration to worker.
I've tested it with my current project using tsconfig-paths and it seems to work without issues.

It's just one-liner so if you could please merge it as fast as you can I would be very grateful 👍 

Cheers!

### CODE REVIEW

**Comment by niftylettuce** [comment]
Please fix linting

**Comment by shadowgate15** [comment]
also you need to add a peerDepedency for tsconfig-paths.

**Comment by kgkg** [comment]
Fixed linting and added peerDeps :)

**Comment by niftylettuce** [comment]
Since this is TS I'll let you handle @shadowgate15 😏

**Comment by shadowgate15** [comment]
can you also added it as a devDep @kgkg?

**Comment by shadowgate15** [comment]
and also for those peer deps lets use ">=NUM"

**Comment by shadowgate15** [comment]
can you update lockfile?

**Comment by shadowgate15** [comment]
nvm I'll take care of it.

**Comment by shadowgate15** [comment]
published https://github.com/breejs/ts-worker/releases/tag/v1.1.0

**Comment by kgkg** [comment]
Great news, thank you 🎉

**Comment by kgkg** [comment]
@shadowgate15 unfortunately doesn't work with npm :/
```
$ npm install @breejs/ts-worker
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=3<4": Tags may not have any characters that encodeURIComponent encodes.
```

Probably needs to be ">=3 <4"

**Comment by shadowgate15** [comment]
fixed https://github.com/breejs/ts-worker/releases/tag/v1.1.1

**Pull request merged**
